CREATE OR REPLACE FUNCTION FN_TABLA_1_QUE_QUIERO_HACER_INSERT_UPDATE()
RETURNS Trigger AS $$
DECLARE cant Integer;
    BEGIN
    SELECT COUNT(*) AS cant
    FROM TABLA_2_A_LA_QUE_LLAMO
    WHERE atributo=NEW.atributo;
    IF(cant>0)
    THEN RAISE EXCEPTION 'error';
    END IF;
RETURN NEW;
END $$
LANGUAGE 'plpgsql';

CREATE TRIGGER TR_TABLA_1_QUE_QUIERO_HACER_INSERT_UPDATE
    BEFORE INSERT OR UPDATE OF columnas
           ON TABLA_QUE_QUIERO_HACER_INSERT_UPDATE
           FOR EACH ROW EXECUTE PROCEDURE FN_...();